language: ruby
cache: bundler
rvm:
- 2.3.1
branches:
  only:
    - gh-pages
install:
- bundle install --path=vendor/bundle --jobs=4 --retry=3
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: gh-pages
