# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Travel Size Life
email: hello@travelsizelife.com
description: >
  Travel Site
baseurl: ""
url: "https://travelsizelife.com"
permalink: none

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - travelsize_jekyll

sass:
  sass_dir: _sass


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
